name: rdap
base: core22
version: '2022.09.08+git'  # This is basically the date of last revision.
summary: RDAP command line client, written in Go
description: |
  OpenRDAP is a command line client for the Registration Data Access 
  Protocol, written in Go. RDAP is a replacement for WHOIS, which provides 
  domain name & IP address registration information in JSON format over 
  HTTP.

grade: stable 
confinement: strict

parts:
  rdap:
    # See 'snapcraft plugins'
    plugin: go
    source-type: git
    source: https://github.com/teward/rdap

apps:
  rdap:
    command: bin/rdap
    plugs:
      - home
      - network
